# Generated by Django 4.1.9 on 2023-06-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_customerdata_order_orderproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents")),
                (
                    "doc_type",
                    models.CharField(choices=[("agreement", "Agreement"), ("receipt", "Receipt")], max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="store.order"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.documenttemplate"),
                ),
            ],
        ),
    ]
