# Generated by Django 4.1.9 on 2023-06-22 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdocument",
            name="sent",
        ),
    ]
