# Generated by Django 4.1.9 on 2023-06-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_documenttemplate_orderdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="orderdocument",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
