# Generated by Django 4.1.10 on 2023-08-04 03:05

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_remove_orderdocument_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=""),
        ),
    ]
