# Generated by Django 4.1.9 on 2023-06-25 19:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_rename_productimage_producttemplateimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="info",
        ),
        migrations.AddField(
            model_name="producttemplateimage",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="producttemplateimage",
            name="template",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="template_images", to="store.producttemplate"
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="")),
                ("is_main", models.BooleanField(default=False)),
                (
                    "product",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="product_images", to="store.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
