# Generated by Django 4.1.10 on 2023-08-08 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_productimage_image"),
        ("store", "0012_deliverymethod_order_uuid_product_uuid_and_more"),
    ]

    operations = []
