# Generated by Django 4.1.9 on 2023-06-25 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_remove_orderdocument_sent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductImage",
            new_name="ProductTemplateImage",
        ),
    ]
