# Generated by Django 4.1.9 on 2023-06-30 16:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_remove_product_info_producttemplateimage_is_main_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategoryParamValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=255)),
                (
                    "param",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="param_values",
                        to="store.productcategoryparam",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
