# Generated by Django 4.1.9 on 2023-07-02 09:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_auto_20230630_1611"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductParam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "param_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.productcategoryparamvalue"
                    ),
                ),
                (
                    "product",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="product_params", to="store.product"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TemplateParamValue",
        ),
        migrations.AddField(
            model_name="product",
            name="params",
            field=models.ManyToManyField(
                blank=True, through="store.ProductParam", to="store.productcategoryparamvalue"
            ),
        ),
    ]
