version: "3.8"
services:
  test_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_ROOT_PASSWORD=password
      - POSTGRES_USER=comfy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=comfy_shop
    volumes:
      - ../postgres/:/var/lib/postgresql
  test_comfy:
    depends_on:
      - test_db
    build:
      dockerfile: Dockerfile.local
      context: ./
    user: "${UID}:${GID}"
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY=RandomKey
      - DATABASE_URL=postgres://comfy:password@test_db/comfy_shop
      - DJANGO_SETTINGS_MODULE=artel.settings.tests
    command:
      python manage.py test --noinput
