version: "3.8"
services:
  comfy:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY
      - DATABASE_URL
      - DJANGO_SETTINGS_MODULE
    env_file:
      - .env
    
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_ROOT_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ../postgres/:/var/lib/postgresql
    env_file:
      - .env
