version: "3.8"
services:
  smtp-server:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"  
  comfy:
    depends_on:
      - smtp-server
      - db
    build:
      dockerfile: Dockerfile.local
      context: ./
    user: "${UID}:${GID}"
    ports:
      - "8001:8000"
    volumes:
#      - ./:/app
      - media:/app/media
    environment:
      - SECRET_KEY
      - DATABASE_URL
    env_file:
      - .env
    stdin_open: true
    tty: true
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_ROOT_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - "8002:8080"


volumes:
  media:
  db:
