version: "3.8"
services:
  smtp-server:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"  
  comfy:
    depends_on:
      - smtp-server
      - db
    build:
      dockerfile: Dockerfile.local
      context: ./
    user: "${UID}:${GID}"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY
      - DATABASE_URL
    env_file:
      - .env
    stdin_open: true
    tty: true
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_ROOT_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ../postgres/:/var/lib/postgresql
    env_file:
      - .env
