# Generated by Django 4.1.9 on 2023-06-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logo/")),
                ("shop_enabled", models.BooleanField(default=True)),
                ("homepage", models.CharField(blank=True, max_length=255, null=True)),
                ("navbar_position", models.CharField(default="left", max_length=20)),
            ],
        ),
    ]
