# Generated by Django 4.1.10 on 2023-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comfyconfig",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
