# Generated by Django 4.1.9 on 2023-06-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="isSetup",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/icons"),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="navbar_position",
            field=models.CharField(choices=[("left", "Left"), ("right", "Right")], default="left", max_length=20),
        ),
    ]
